export const START_FETCH = 'START_FETCH';
export const END_FETCH = 'END_FETCH'; 
export const SAVE_PACKAGES_LIST = 'SAVE_PACKAGES_LIST';
export const CLEAR_PACKAGES_LIST = 'CLEAR_PACKAGES_LIST';
export const SAVE_TARGET_PACKAGE = 'SAVE_TARGET_PACKAGE';
export const CLEAR_TARGET_PACKAGE = 'CLEAR_TARGET_PACKAGE';